### PR TITLE
Improve syntax highlighting of Swift code.

### PR DESCRIPTION
**Pull request by furby-tm**
Adds improved syntax highlighting of:
- `import` statements
- `#if` preprocessor statements
- as well as `/** */` comments
 
Which all otherwise appear in full opacity white color (without syntax highlighting) and makes it difficult to read & write Swift code.

**Screenshots**
328725936-f970bf3f-6401-46ce-89e5-bdadad313dfa

328726244-97cedc50-0056-4cd6-9acd-c50fe7c530b2

### CODE REVIEW

**Comment by furby-tm** [comment]
Hopefully we can get this in before the extension goes live in this [**PR**](https://github.com/zed-extensions/swift/pull/6).

**Comment by furby-tm** [comment]
I went back through the highlighting config carefully, I think I got things looking great now, here's the comparison after that last commit:

Now (Current Changes)      |  Before (Ugly Old Changes)
:-------------------------:|:-------------------------:
 |

**Comment by furby-tm** [comment]
ScreenCapture_2024-05-09_at_00 13 51

After the final revisions. 👍🏻

**Comment by cyypherus** [comment]
Closing in favor of cherry picked commits https://github.com/ejjonny/swift/pull/2

**Pull request closed without merging**
